[project]
name = "veronica-mineru-pdf2md"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "aiohttp>=3.13.3",
    "httpx>=0.28.1",
    "pymongo>=4.16.0",
    "requests>=2.32.5",
]
